repos:
  - repo: local
    hooks:
      - id: run-guacamole-tests
        name: Run guacamole tests
        entry: python manage.py test guacamole/tests
        language: system
        pass_filenames: false
